# Numpy

In [2]:
import numpy as np

### Basic Array Creation

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
#if we write list
a = [1,2,3,4,'hello']
a

[1, 2, 3, 4, 'hello']

In [6]:
#if we put multiple data types on array ; it will convert it into string ,if we not pass the string it will convert it into float
arr = np.array([1,2,3,4,5.0,'hello'])
arr

array(['1', '2', '3', '4', '5.0', 'hello'], dtype='<U32')

In [7]:
arr = np.array([1,2,3,4.0])
arr

array([1., 2., 3., 4.])

In [9]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
l = np.array(l)
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array generation functions

In [4]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [8]:
arr = np.zeros((6,6)) #6 rows and 6 columns
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
#4 rows and 6 columns
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
#linspace divide numbers
arr = np.linspace(1,10,7)
arr

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

### Random Generation function

In [17]:
arr = np.random.rand(5)
arr

array([0.1594552 , 0.48030645, 0.437599  , 0.75789299, 0.54523876])

In [31]:
arr = np.random.randn(10) #randn will give values from -3 to 3 also called standardization
arr

array([-2.12399387, -0.46641253,  0.66312781,  1.12341858,  0.19177599,
        1.16267665, -1.52564893, -1.79198826, -1.0111057 ,  0.15742575])

In [32]:
arr = np.random.randint(1,10,20) #start value - stop value - no.of value
arr

array([4, 5, 1, 9, 5, 6, 3, 5, 5, 7, 1, 1, 9, 1, 9, 4, 3, 5, 5, 4])

### Array Attributes

In [35]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.shape

(3, 3)

In [37]:
arr.size

9

In [38]:
arr.dtype

dtype('int64')

### Array methods

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [45]:
np.sum(arr,axis=0) #calculate the sum of column

array([12, 15, 18])

In [46]:
np.sum(arr,axis=1) #calculate the sum of row

array([ 6, 15, 24])

In [47]:
arr.mean()

np.float64(5.0)

In [48]:
arr.std()

np.float64(2.581988897471611)

In [49]:
arr.argmax() #display the index of maximum number

np.int64(8)

In [50]:
arr.argmin() #display the index of minimum number

np.int64(0)

### Reshaping and resizing

In [52]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Arrays Indexing and Slicing

In [54]:
import numpy as np

In [55]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
arr[5]

np.int64(16)

In [60]:
#print values 12 to 15
arr[1:5]

array([12, 13, 14, 15])

### Numpy Indexig and Slicing of Matrix

In [61]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [62]:
arr[0]

array([1, 2, 3, 4, 5])

In [63]:
arr[4]

array([21, 22, 23, 24, 25])

In [80]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

### Boolean Indexing

In [81]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [82]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [83]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])